export const HIDE_SETTING  = 'HIDE_SETTING';
export const SHOW_SETTING  = 'SHOW_SETTING';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_LOGO = 'CHANGE_LOGO';
export const SET_COMPONENT = 'SET_COMPONENT';
export const SET_HEADER = 'SET_HEADER';
export const CHANGE_PAGE_CONTENT = 'CHANGE_PAGE_CONTENT';
export const CHANGE_SETTING = 'CHANGE_SETTING';
