export const articleProps = {
	title: 'New Article',
	slug: '',
	path: '',
	meta: '',
	page_css: '',
	page_js: '',
	author: '',
	thumbnail: '',
	categories: [],
	publish_date: '',
	status: 0,
	content: [],
	comments: [],
};
